audio:
  sample_rate: 44100
  channels: 1
  chunk_size: 1024
  format: "int16"
  
recording:
  output_dir: "./recordings"
  file_prefix: "call_"
  max_duration: 3600  # 1小时
  
auto_recording:
  enabled: false  # 是否启用自动录制
  volume_threshold: 0.015  # 音量阈值（0-1）
  start_duration: 3.0  # 开始录制前的检测时长（秒）
  end_silence_duration: 12.0  # 结束录制的静默时长（秒）
  min_call_duration: 5.0  # 最短通话时长（秒）
  check_interval: 0.5  # 检测间隔（秒）
  buffer_duration: 30.0  # 循环缓冲区时长（秒）
  
upload:
  enabled: true
  type: "oss_with_server"
  token_url: "https://www.rocksilicon.com/api/get-upload-token"
  notify_url: "https://www.rocksilicon.com/api/upload-complete"
  timeout: 60
  auto_delete: false
  retry_times: 3