audio:
  sample_rate: 44100
  channels: 1
  chunk_size: 1024
  format: "int16"
  
recording:
  output_dir: "./recordings"
  file_prefix: "call_"
  max_duration: 3600  # 1小时
  
upload:
  enabled: true
  type: "oss_with_server"
  token_url: "https://www.rocksilicon.com/api/get-upload-token"
  notify_url: "https://www.rocksilicon.com/api/upload-complete"
  timeout: 60
  auto_delete: false
  retry_times: 3